name: KotlinPluginCore
version: '${version}'
description: '${description}'
main: com.jifercraft.core.CorePlugin
api-version: '1.21.4'
author: JainaGam3r45
website: https://www.jifercraft.com

permissions:
  core.help:
    default: true
  core.reload:
    default: op
  core.debug:
    default: op
